#define CFG_TUSB_MCU OPT_MCU_STM32F4
#define CFG_TUSB_OS OPT_OS_FREERTOS
#define CFG_TUD_ENABLED 1
#define CFG_USBIP_DWC2 1
#define CFG_TUD_HID 1
#define CFG_TUD_ENDPOINT0_SIZE    64
#define CFG_TUD_HID_EP_BUFSIZE    64
#define CFG_TUSB_DEBUG 0
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
